# Generated by Django 3.1 on 2020-09-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='ee', max_length=255, upload_to='pictures/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
