# Generated by Django 3.1 on 2020-09-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20200904_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='dd', max_length=255, upload_to='pictures/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
