# Generated by Django 3.1 on 2020-09-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.chapter'),
            preserve_default=False,
        ),
    ]
