# Generated by Django 3.1 on 2020-09-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
