# Generated by Django 3.1 on 2020-09-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
