# Generated by Django 3.1 on 2020-09-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_table1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
